export type Category =
  | "all"
  | "arcade"
  | "puzzle"
  | "reflex"
  | "creative"
  | "simulation"
  | "trivia"
  | "multiplayer"
  | "deep";

export interface Game {
  id: string;
  title: string;
  description: string;
  icon: string;
  path: string;
  category: Exclude<Category, "all" | "deep">;
  isNew: boolean;
  isDeep?: boolean;
  playerCount?: string;
}

export const games: Game[] = [
  // Original games
  {
    id: "slevens",
    title: "Slevens",
    description: "Shake to roll dice drinking game",
    icon: "\uD83C\uDFB2",
    path: "/games/slevens",
    category: "arcade",
    isNew: false,
  },
  {
    id: "snakes",
    title: "Snake Game",
    description: "Classic snake with pixel art",
    icon: "\uD83D\uDC0D",
    path: "/games/snakes",
    category: "arcade",
    isNew: false,
  },
  // Phase 1 games
  {
    id: "salary",
    title: "The Salary Game",
    description: "Can you spend a dev salary?",
    icon: "\uD83D\uDCB0",
    path: "/games/salary",
    category: "simulation",
    isNew: true,
  },
  {
    id: "reflex-duel",
    title: "Reflex Duel",
    description: "Cowboy reaction time test",
    icon: "\uD83E\uDD20",
    path: "/games/reflex-duel",
    category: "reflex",
    isNew: true,
  },
  {
    id: "color-guesser",
    title: "Color Guesser",
    description: "Match hex codes to colors",
    icon: "\uD83C\uDFA8",
    path: "/games/color-guesser",
    category: "trivia",
    isNew: true,
  },
  {
    id: "type-racer",
    title: "Type Racer",
    description: "Speed typing with pixel car",
    icon: "\u2328\uFE0F",
    path: "/games/type-racer",
    category: "reflex",
    isNew: true,
  },
  {
    id: "pixel-painter",
    title: "Pixel Art Painter",
    description: "Draw pixel art, save it, start another",
    icon: "\uD83D\uDD8C\uFE0F",
    path: "/games/pixel-painter",
    category: "creative",
    isNew: true,
  },
  {
    id: "perfect-shape",
    title: "Draw Perfect Shape",
    description: "How steady is your hand?",
    icon: "\u270F\uFE0F",
    path: "/games/perfect-shape",
    category: "creative",
    isNew: true,
  },
  {
    id: "pixel-perfector",
    title: "Pixel Perfector",
    description: "Memorize and recreate pixel art",
    icon: "\uD83D\uDC7E",
    path: "/games/pixel-perfector",
    category: "puzzle",
    isNew: true,
  },
  // Phase 2 games
  {
    id: "stack-tower",
    title: "Stack Tower",
    description: "Stack blocks, don't miss!",
    icon: "\uD83C\uDFD7\uFE0F",
    path: "/games/stack-tower",
    category: "arcade",
    isNew: true,
  },
  {
    id: "orbit",
    title: "Orbit",
    description: "N-body gravity simulator",
    icon: "\uD83E\uDE90",
    path: "/games/orbit",
    category: "simulation",
    isNew: true,
  },
  {
    id: "breakout",
    title: "Breakout Remix",
    description: "Smash bricks with power-ups",
    icon: "\uD83E\uDDF1",
    path: "/games/breakout",
    category: "arcade",
    isNew: true,
  },
  {
    id: "flappy",
    title: "Flappy Pixel",
    description: "Pixel-art flappy bird",
    icon: "\uD83D\uDC26",
    path: "/games/flappy",
    category: "arcade",
    isNew: true,
  },
  {
    id: "minesweeper",
    title: "Minesweeper",
    description: "Classic mine-sweeping puzzle",
    icon: "\uD83D\uDCA3",
    path: "/games/minesweeper",
    category: "puzzle",
    isNew: true,
  },
  {
    id: "maze-runner",
    title: "Maze Runner",
    description: "Navigate through fog of war",
    icon: "\uD83C\uDF00",
    path: "/games/maze-runner",
    category: "puzzle",
    isNew: true,
  },
  {
    id: "code-quiz",
    title: "Code Quiz",
    description: "150+ questions across 8 tech categories",
    icon: "{ }",
    path: "/games/code-quiz",
    category: "trivia",
    isNew: true,
  },
  {
    id: "idle-bakery",
    title: "Idle Bakery",
    description: "Bake bread and grow your bakery",
    icon: "\uD83C\uDF5E",
    path: "/games/idle-bakery",
    category: "simulation",
    isNew: true,
  },
  // Multiplayer games
  {
    id: "pixel-impostor",
    title: "Pixel Impostor",
    description: "One word, one liar, find the fake",
    icon: "\uD83D\uDD75\uFE0F",
    path: "/games/pixel-impostor",
    category: "multiplayer",
    isNew: true,
    playerCount: "3-8 players",
  },
  {
    id: "spyfall-dev",
    title: "Spyfall: Dev Edition",
    description: "Everyone knows the location... except the spy",
    icon: "\uD83D\uDD0D",
    path: "/games/spyfall-dev",
    category: "multiplayer",
    isNew: true,
    playerCount: "4-10 players",
  },
  {
    id: "person-do-thing",
    title: "Person Do Thing",
    description: "Describe anything with only 34 words",
    icon: "\uD83D\uDDE3\uFE0F",
    path: "/games/person-do-thing",
    category: "multiplayer",
    isNew: true,
    playerCount: "3-8 players · one device",
  },
  {
    id: "prompt-roulette",
    title: "Prompt Roulette",
    description: "Write the funniest answer, everyone votes",
    icon: "\uD83C\uDFB0",
    path: "/games/prompt-roulette",
    category: "multiplayer",
    isNew: true,
    playerCount: "3-10 players",
  },
  {
    id: "wavelength",
    title: "Wavelength",
    description: "Guess where the clue falls on the spectrum",
    icon: "\uD83D\uDCE1",
    path: "/games/wavelength",
    category: "multiplayer",
    isNew: true,
    playerCount: "2-12 players",
  },
  {
    id: "stack-overflow",
    title: "Stack Overflow",
    description: "Real tech facts vs convincing lies",
    icon: "\uD83D\uDCDA",
    path: "/games/stack-overflow",
    category: "multiplayer",
    isNew: true,
    playerCount: "3-8 players",
  },
  {
    id: "merge-conflict",
    title: "Merge Conflict",
    description: "Two devs, one function, zero communication",
    icon: "\uD83D\uDD00",
    path: "/games/merge-conflict",
    category: "multiplayer",
    isNew: true,
    playerCount: "2–8 players",
  },
  {
    id: "dev-trivia",
    title: "Dev Trivia Showdown",
    description: "Team programming trivia with wagering",
    icon: "\uD83C\uDFC6",
    path: "/games/dev-trivia",
    category: "multiplayer",
    isNew: true,
    playerCount: "2-8 players",
  },
  {
    id: "glitch-artist",
    title: "Glitch Artist",
    description: "Everyone draws, one player fakes it",
    icon: "\uD83C\uDFA8",
    path: "/games/glitch-artist",
    category: "multiplayer",
    isNew: true,
    playerCount: "4-8 players · one device",
  },
  {
    id: "retro-reflex",
    title: "Retro Reflex Duel",
    description: "Rapid-fire micro-challenges",
    icon: "\u26A1",
    path: "/games/retro-reflex",
    category: "multiplayer",
    isNew: true,
    playerCount: "2-4 players · one device",
  },
  // Solo deep games
  {
    id: "alignment-problem",
    title: "The Alignment Problem",
    description: "Train an AI, watch it find loopholes",
    icon: "\uD83E\uDD16",
    path: "/games/alignment-problem",
    category: "simulation",
    isNew: true,
    isDeep: true,
  },
  {
    id: "ecosystem",
    title: "Ecosystem Architect",
    description: "Design ecosystems, watch life emerge",
    icon: "\uD83C\uDF3F",
    path: "/games/ecosystem",
    category: "simulation",
    isNew: true,
    isDeep: true,
  },
  {
    id: "galactic-census",
    title: "Galactic Census",
    description: "Survey alien civilizations across the galaxy",
    icon: "\uD83D\uDEF8",
    path: "/games/galactic-census",
    category: "puzzle",
    isNew: true,
    isDeep: true,
  },
  {
    id: "deja-vu",
    title: "Deja Vu",
    description: "Escape a room that keeps resetting",
    icon: "\uD83D\uDD04",
    path: "/games/deja-vu",
    category: "puzzle",
    isNew: true,
    isDeep: true,
  },
  {
    id: "code-review",
    title: "Code Review From Hell",
    description: "Satisfy impossible review comments",
    icon: "\uD83E\uDD13",
    path: "/games/code-review",
    category: "puzzle",
    isNew: true,
    isDeep: true,
  },
  {
    id: "tos-game",
    title: "Terms of Service",
    description: "Find the absurd clauses in legal text",
    icon: "\uD83D\uDCDC",
    path: "/games/tos-game",
    category: "puzzle",
    isNew: true,
    isDeep: true,
  },
];
