export interface WordPair {
  real: string;
  decoy: string;
}

export interface WordCategory {
  name: string;
  icon: string;
  pairs: WordPair[];
}

export const WORD_CATEGORIES: WordCategory[] = [
  {
    name: 'Animals',
    icon: '\uD83D\uDC3E',
    pairs: [
      { real: 'Wolf', decoy: 'Fox' },
      { real: 'Eagle', decoy: 'Hawk' },
      { real: 'Dolphin', decoy: 'Whale' },
      { real: 'Tiger', decoy: 'Lion' },
      { real: 'Penguin', decoy: 'Puffin' },
      { real: 'Cobra', decoy: 'Viper' },
      { real: 'Gorilla', decoy: 'Chimpanzee' },
      { real: 'Shark', decoy: 'Barracuda' },
      { real: 'Owl', decoy: 'Raven' },
      { real: 'Rabbit', decoy: 'Hamster' },
      { real: 'Crocodile', decoy: 'Alligator' },
      { real: 'Parrot', decoy: 'Toucan' },
      { real: 'Cheetah', decoy: 'Leopard' },
      { real: 'Octopus', decoy: 'Squid' },
      { real: 'Turtle', decoy: 'Tortoise' },
      { real: 'Deer', decoy: 'Elk' },
      { real: 'Salmon', decoy: 'Trout' },
      { real: 'Butterfly', decoy: 'Moth' },
      { real: 'Flamingo', decoy: 'Crane' },
      { real: 'Scorpion', decoy: 'Spider' },
    ],
  },
  {
    name: 'Food',
    icon: '\uD83C\uDF54',
    pairs: [
      { real: 'Sushi', decoy: 'Ramen' },
      { real: 'Pizza', decoy: 'Calzone' },
      { real: 'Burger', decoy: 'Hotdog' },
      { real: 'Pancake', decoy: 'Waffle' },
      { real: 'Croissant', decoy: 'Baguette' },
      { real: 'Taco', decoy: 'Burrito' },
      { real: 'Steak', decoy: 'Ribs' },
      { real: 'Donut', decoy: 'Bagel' },
      { real: 'Pasta', decoy: 'Noodles' },
      { real: 'Ice Cream', decoy: 'Gelato' },
      { real: 'Curry', decoy: 'Stew' },
      { real: 'Sausage', decoy: 'Bacon' },
      { real: 'Muffin', decoy: 'Cupcake' },
      { real: 'Nachos', decoy: 'Chips' },
      { real: 'Soup', decoy: 'Broth' },
      { real: 'Omelette', decoy: 'Frittata' },
      { real: 'Cheesecake', decoy: 'Tiramisu' },
      { real: 'Lobster', decoy: 'Crab' },
      { real: 'Smoothie', decoy: 'Milkshake' },
      { real: 'Popcorn', decoy: 'Pretzels' },
    ],
  },
  {
    name: 'Places',
    icon: '\uD83C\uDF0D',
    pairs: [
      { real: 'Paris', decoy: 'London' },
      { real: 'Mars', decoy: 'Jupiter' },
      { real: 'Beach', decoy: 'Lake' },
      { real: 'Desert', decoy: 'Savanna' },
      { real: 'Tokyo', decoy: 'Seoul' },
      { real: 'Amazon', decoy: 'Congo' },
      { real: 'Antarctica', decoy: 'Arctic' },
      { real: 'Volcano', decoy: 'Geyser' },
      { real: 'Castle', decoy: 'Palace' },
      { real: 'Hospital', decoy: 'Clinic' },
      { real: 'Library', decoy: 'Bookstore' },
      { real: 'Stadium', decoy: 'Arena' },
      { real: 'Museum', decoy: 'Gallery' },
      { real: 'Airport', decoy: 'Station' },
      { real: 'Pyramid', decoy: 'Temple' },
      { real: 'Island', decoy: 'Peninsula' },
      { real: 'Cave', decoy: 'Tunnel' },
      { real: 'Waterfall', decoy: 'Rapids' },
      { real: 'Lighthouse', decoy: 'Tower' },
      { real: 'Jungle', decoy: 'Forest' },
    ],
  },
  {
    name: 'Tech',
    icon: '\uD83D\uDCBB',
    pairs: [
      { real: 'Python', decoy: 'JavaScript' },
      { real: 'React', decoy: 'Vue' },
      { real: 'Docker', decoy: 'Kubernetes' },
      { real: 'GitHub', decoy: 'GitLab' },
      { real: 'Linux', decoy: 'Windows' },
      { real: 'Bluetooth', decoy: 'WiFi' },
      { real: 'Bitcoin', decoy: 'Ethereum' },
      { real: 'ChatGPT', decoy: 'Gemini' },
      { real: 'Tesla', decoy: 'SpaceX' },
      { real: 'Pixel', decoy: 'Voxel' },
      { real: 'Algorithm', decoy: 'Heuristic' },
      { real: 'Database', decoy: 'Spreadsheet' },
      { real: 'Firewall', decoy: 'Antivirus' },
      { real: 'Router', decoy: 'Modem' },
      { real: 'Tablet', decoy: 'Laptop' },
      { real: 'Drone', decoy: 'Robot' },
      { real: 'Podcast', decoy: 'Audiobook' },
      { real: 'VPN', decoy: 'Proxy' },
      { real: 'Cloud', decoy: 'Server' },
      { real: 'Twitch', decoy: 'YouTube' },
    ],
  },
  {
    name: 'Movies',
    icon: '\uD83C\uDFAC',
    pairs: [
      { real: 'Titanic', decoy: 'Poseidon' },
      { real: 'Jaws', decoy: 'Piranha' },
      { real: 'Matrix', decoy: 'Inception' },
      { real: 'Avatar', decoy: 'Alien' },
      { real: 'Rocky', decoy: 'Rambo' },
      { real: 'Frozen', decoy: 'Tangled' },
      { real: 'Batman', decoy: 'Superman' },
      { real: 'Shrek', decoy: 'Donkey' },
      { real: 'Gladiator', decoy: 'Spartacus' },
      { real: 'Jurassic', decoy: 'Godzilla' },
      { real: 'Toy Story', decoy: 'Monsters Inc' },
      { real: 'Star Wars', decoy: 'Star Trek' },
      { real: 'Joker', decoy: 'Riddler' },
      { real: 'Bond', decoy: 'Bourne' },
      { real: 'Hobbit', decoy: 'Narnia' },
      { real: 'Predator', decoy: 'Terminator' },
      { real: 'Avengers', decoy: 'Justice League' },
      { real: 'Coco', decoy: 'Moana' },
      { real: 'Dune', decoy: 'Blade Runner' },
      { real: 'Scarface', decoy: 'Godfather' },
    ],
  },
  {
    name: 'Sports',
    icon: '\u26BD',
    pairs: [
      { real: 'Soccer', decoy: 'Rugby' },
      { real: 'Tennis', decoy: 'Badminton' },
      { real: 'Boxing', decoy: 'Wrestling' },
      { real: 'Surfing', decoy: 'Skateboarding' },
      { real: 'Golf', decoy: 'Cricket' },
      { real: 'Hockey', decoy: 'Lacrosse' },
      { real: 'Marathon', decoy: 'Sprint' },
      { real: 'Archery', decoy: 'Fencing' },
      { real: 'Skiing', decoy: 'Snowboarding' },
      { real: 'Volleyball', decoy: 'Handball' },
      { real: 'Baseball', decoy: 'Softball' },
      { real: 'Karate', decoy: 'Judo' },
      { real: 'Rowing', decoy: 'Kayaking' },
      { real: 'Diving', decoy: 'Swimming' },
      { real: 'Polo', decoy: 'Equestrian' },
      { real: 'Darts', decoy: 'Billiards' },
      { real: 'Bowling', decoy: 'Curling' },
      { real: 'Triathlon', decoy: 'Decathlon' },
      { real: 'NASCAR', decoy: 'Formula 1' },
      { real: 'Yoga', decoy: 'Pilates' },
    ],
  },
  {
    name: 'Nature',
    icon: '\uD83C\uDF3F',
    pairs: [
      { real: 'Tornado', decoy: 'Hurricane' },
      { real: 'Mountain', decoy: 'Hill' },
      { real: 'Ocean', decoy: 'Sea' },
      { real: 'Lightning', decoy: 'Thunder' },
      { real: 'Sunrise', decoy: 'Sunset' },
      { real: 'Rainbow', decoy: 'Aurora' },
      { real: 'Glacier', decoy: 'Iceberg' },
      { real: 'Earthquake', decoy: 'Landslide' },
      { real: 'Coral', decoy: 'Seaweed' },
      { real: 'Fossil', decoy: 'Crystal' },
      { real: 'Cactus', decoy: 'Succulent' },
      { real: 'Mushroom', decoy: 'Moss' },
      { real: 'Bamboo', decoy: 'Reed' },
      { real: 'Meteor', decoy: 'Comet' },
      { real: 'Tsunami', decoy: 'Flood' },
      { real: 'Eclipse', decoy: 'Solstice' },
      { real: 'Oasis', decoy: 'Mirage' },
      { real: 'Avalanche', decoy: 'Blizzard' },
      { real: 'Pebble', decoy: 'Boulder' },
      { real: 'River', decoy: 'Stream' },
    ],
  },
  {
    name: 'Music',
    icon: '\uD83C\uDFB5',
    pairs: [
      { real: 'Piano', decoy: 'Guitar' },
      { real: 'Drums', decoy: 'Bongos' },
      { real: 'Violin', decoy: 'Cello' },
      { real: 'Trumpet', decoy: 'Trombone' },
      { real: 'DJ', decoy: 'Rapper' },
      { real: 'Opera', decoy: 'Musical' },
      { real: 'Choir', decoy: 'Band' },
      { real: 'Reggae', decoy: 'Ska' },
      { real: 'Jazz', decoy: 'Blues' },
      { real: 'Concert', decoy: 'Festival' },
      { real: 'Karaoke', decoy: 'Lip Sync' },
      { real: 'Vinyl', decoy: 'Cassette' },
      { real: 'Flute', decoy: 'Clarinet' },
      { real: 'Harp', decoy: 'Lyre' },
      { real: 'Ukulele', decoy: 'Banjo' },
      { real: 'Soprano', decoy: 'Alto' },
      { real: 'Dubstep', decoy: 'Techno' },
      { real: 'Acoustic', decoy: 'Electric' },
      { real: 'Harmony', decoy: 'Melody' },
      { real: 'Ballad', decoy: 'Anthem' },
    ],
  },
  {
    name: 'Occupations',
    icon: '\uD83D\uDC77',
    pairs: [
      { real: 'Surgeon', decoy: 'Dentist' },
      { real: 'Pilot', decoy: 'Captain' },
      { real: 'Chef', decoy: 'Baker' },
      { real: 'Architect', decoy: 'Engineer' },
      { real: 'Detective', decoy: 'Spy' },
      { real: 'Lawyer', decoy: 'Judge' },
      { real: 'Astronaut', decoy: 'Scientist' },
      { real: 'Plumber', decoy: 'Electrician' },
      { real: 'Barista', decoy: 'Bartender' },
      { real: 'Author', decoy: 'Poet' },
      { real: 'Painter', decoy: 'Sculptor' },
      { real: 'Magician', decoy: 'Comedian' },
      { real: 'Firefighter', decoy: 'Paramedic' },
      { real: 'Teacher', decoy: 'Professor' },
      { real: 'Photographer', decoy: 'Filmmaker' },
      { real: 'Journalist', decoy: 'Blogger' },
      { real: 'Therapist', decoy: 'Counselor' },
      { real: 'Mechanic', decoy: 'Technician' },
      { real: 'Florist', decoy: 'Gardener' },
      { real: 'Librarian', decoy: 'Archivist' },
    ],
  },
  {
    name: 'Household',
    icon: '\uD83C\uDFE0',
    pairs: [
      { real: 'Sofa', decoy: 'Recliner' },
      { real: 'Lamp', decoy: 'Candle' },
      { real: 'Oven', decoy: 'Microwave' },
      { real: 'Blanket', decoy: 'Pillow' },
      { real: 'Mirror', decoy: 'Window' },
      { real: 'Fridge', decoy: 'Freezer' },
      { real: 'Bathtub', decoy: 'Shower' },
      { real: 'Broom', decoy: 'Mop' },
      { real: 'Toaster', decoy: 'Kettle' },
      { real: 'Scissors', decoy: 'Knife' },
      { real: 'Closet', decoy: 'Drawer' },
      { real: 'Curtain', decoy: 'Blind' },
      { real: 'Doorbell', decoy: 'Knocker' },
      { real: 'Vacuum', decoy: 'Duster' },
      { real: 'Clock', decoy: 'Timer' },
      { real: 'Vase', decoy: 'Pot' },
      { real: 'Towel', decoy: 'Napkin' },
      { real: 'Toolbox', decoy: 'Toolkit' },
      { real: 'Fireplace', decoy: 'Heater' },
      { real: 'Garage', decoy: 'Shed' },
    ],
  },
];

export function getRandomPair(categoryNames?: string[]): { pair: WordPair; category: string } {
  const filtered =
    categoryNames && categoryNames.length > 0
      ? WORD_CATEGORIES.filter((c) => categoryNames.includes(c.name))
      : WORD_CATEGORIES;

  const category = filtered[Math.floor(Math.random() * filtered.length)];
  const pair = category.pairs[Math.floor(Math.random() * category.pairs.length)];
  return { pair, category: category.name };
}

export function getTotalPairCount(): number {
  return WORD_CATEGORIES.reduce((sum, cat) => sum + cat.pairs.length, 0);
}
