import type { ManualCatalogCity } from "./types";

const EMPTY_VISIT_AGGREGATE = {
  population: 0,
  visitCount: 0,
  spotCount: 0,
  dwellMs: 0,
  firstSeen: null,
  lastSeen: null,
  years: [],
} satisfies Pick<
  ManualCatalogCity,
  | "population"
  | "visitCount"
  | "spotCount"
  | "dwellMs"
  | "firstSeen"
  | "lastSeen"
  | "years"
>;

/** Canonical places absent from the generated Timeline aggregate. */
export const MANUAL_CITIES: ManualCatalogCity[] = [
  // May 2025 photo evidence; no synthetic Timeline counts or dwell time.
  {
    ...EMPTY_VISIT_AGGREGATE,
    id: "leissigen",
    name: "Leissigen",
    admin: "BE",
    countryCode: "CH",
    country: "Switzerland",
    flag: "🇨🇭",
    lat: 46.66,
    lng: 7.78,
    years: ["2025"],
  },
  {
    ...EMPTY_VISIT_AGGREGATE,
    id: "wengen",
    name: "Wengen",
    admin: "BE",
    countryCode: "CH",
    country: "Switzerland",
    flag: "🇨🇭",
    lat: 46.605,
    lng: 7.921,
    years: ["2025"],
  },
  {
    ...EMPTY_VISIT_AGGREGATE,
    id: "jungfraujoch",
    name: "Jungfraujoch",
    admin: "",
    countryCode: "CH",
    country: "Switzerland",
    flag: "🇨🇭",
    lat: 46.548,
    lng: 7.985,
    years: ["2025"],
  },
  {
    ...EMPTY_VISIT_AGGREGATE,
    id: "interlaken",
    name: "Interlaken",
    admin: "BE",
    countryCode: "CH",
    country: "Switzerland",
    flag: "🇨🇭",
    lat: 46.686,
    lng: 7.863,
    years: ["2025"],
  },
  // July 2024 photo evidence records the Milner Pass area within the park.
  {
    ...EMPTY_VISIT_AGGREGATE,
    id: "rocky-mountain-national-park",
    name: "Rocky Mountain National Park",
    admin: "CO",
    countryCode: "US",
    country: "United States",
    flag: "🇺🇸",
    lat: 40.42,
    lng: -105.81,
    years: ["2024"],
  },
  // June 2026 photo evidence establishes these destinations. Keep the
  // generated Timeline visit counts and dwell time in their original records.
  {
    ...EMPTY_VISIT_AGGREGATE,
    id: "grand-teton-national-park",
    name: "Grand Teton National Park",
    admin: "WY",
    countryCode: "US",
    country: "United States",
    flag: "🇺🇸",
    lat: 43.8,
    lng: -110.7,
    years: ["2026"],
  },
  {
    ...EMPTY_VISIT_AGGREGATE,
    id: "yellowstone-national-park",
    name: "Yellowstone National Park",
    admin: "WY",
    countryCode: "US",
    country: "United States",
    flag: "🇺🇸",
    lat: 44.6,
    lng: -110.5,
    years: ["2026"],
  },
  {
    ...EMPTY_VISIT_AGGREGATE,
    id: "teton-village",
    name: "Teton Village",
    admin: "WY",
    countryCode: "US",
    country: "United States",
    flag: "🇺🇸",
    lat: 43.5877,
    lng: -110.8278,
    years: ["2026"],
  },
  {
    ...EMPTY_VISIT_AGGREGATE,
    id: "uttar-pradesh",
    name: "Uttar Pradesh",
    admin: "UP",
    countryCode: "IN",
    country: "India",
    flag: "🇮🇳",
    lat: 26.8467,
    lng: 80.9462,
  },
  {
    ...EMPTY_VISIT_AGGREGATE,
    id: "boston-ma",
    name: "Boston",
    admin: "MA",
    countryCode: "US",
    country: "United States",
    flag: "🇺🇸",
    lat: 42.3601,
    lng: -71.0589,
  },
  {
    ...EMPTY_VISIT_AGGREGATE,
    id: "bangalore",
    name: "Bangalore",
    admin: "KA",
    countryCode: "IN",
    country: "India",
    flag: "🇮🇳",
    lat: 12.9716,
    lng: 77.5946,
  },
  {
    ...EMPTY_VISIT_AGGREGATE,
    id: "murphy-tx",
    name: "Murphy",
    admin: "TX",
    countryCode: "US",
    country: "United States",
    flag: "🇺🇸",
    lat: 33.0151,
    lng: -96.613,
  },
  {
    ...EMPTY_VISIT_AGGREGATE,
    id: "richardson-tx",
    name: "Richardson",
    admin: "TX",
    countryCode: "US",
    country: "United States",
    flag: "🇺🇸",
    lat: 32.9482,
    lng: -96.7297,
  },
];
