import type { Point } from "./camera";

export const DRAG_THRESHOLD_PX = 6;
export const DRAG_THRESHOLD_SQUARED = DRAG_THRESHOLD_PX ** 2;

export type CameraMotionPhase =
  | "camera-animating"
  | "zooming"
  | "coasting";

export type InteractionPhase =
  | "idle"
  | "hovering"
  | "pointer-down"
  | "dragging"
  | CameraMotionPhase
  | "selected";

export type ActivationSource = "pointer" | "keyboard" | "programmatic";

export type PointerSession = {
  pointerId: number;
  start: Point;
  current: Point;
};

export type InteractionState = {
  phase: InteractionPhase;
  pointer: PointerSession | null;
  hoveredId: string | null;
  selectedId: string | null;
  /** Armed after a drag until its synthetic pointer click is consumed. */
  suppressPointerClick: boolean;
};

export type InteractionEvent =
  | { type: "POINTER_DOWN"; pointerId: number; point: Point }
  | { type: "POINTER_MOVE"; pointerId: number; point: Point }
  | { type: "POINTER_UP"; pointerId: number }
  | { type: "POINTER_CANCEL"; pointerId: number }
  | { type: "HOVER"; id: string | null }
  | {
      type: "ACTIVATE";
      id: string;
      source: ActivationSource;
    }
  | { type: "DESELECT" }
  | { type: "CAMERA_MOTION_START"; motion: CameraMotionPhase }
  | { type: "CAMERA_MOTION_END"; motion?: CameraMotionPhase }
  | { type: "CLEAR_POINTER_CLICK_SUPPRESSION" }
  | { type: "RESET" };

export type ActivationResult = {
  state: InteractionState;
  activated: boolean;
};

export function createInteractionState(
  initial: {
    hoveredId?: string | null;
    selectedId?: string | null;
  } = {},
): InteractionState {
  const hoveredId = initial.hoveredId ?? null;
  const selectedId = initial.selectedId ?? null;
  return {
    phase: hoveredId ? "hovering" : selectedId ? "selected" : "idle",
    pointer: null,
    hoveredId,
    selectedId,
    suppressPointerClick: false,
  };
}

export function isCameraMotionPhase(
  phase: InteractionPhase,
): phase is CameraMotionPhase {
  return (
    phase === "camera-animating" ||
    phase === "zooming" ||
    phase === "coasting"
  );
}

export function isDragging(state: InteractionState): boolean {
  return state.phase === "dragging";
}

/**
 * Uses a squared comparison so exactly six CSS pixels starts a drag.
 */
export function hasReachedDragThreshold(
  start: Point,
  current: Point,
): boolean {
  const dx = current.x - start.x;
  const dy = current.y - start.y;
  return dx * dx + dy * dy >= DRAG_THRESHOLD_SQUARED;
}

export function pointerDragDelta(state: InteractionState): Point | null {
  if (!state.pointer) return null;
  return {
    x: state.pointer.current.x - state.pointer.start.x,
    y: state.pointer.current.y - state.pointer.start.y,
  };
}

/**
 * Pointer suppression is source-specific: keyboard and programmatic activation
 * remain valid even while a post-drag pointer click is waiting to be consumed.
 */
export function shouldSuppressActivation(
  state: InteractionState,
  source: ActivationSource,
): boolean {
  return source === "pointer" && state.suppressPointerClick;
}

function restingPhase(state: InteractionState): InteractionPhase {
  if (state.hoveredId) return "hovering";
  if (state.selectedId) return "selected";
  return "idle";
}

export function activateInteraction(
  state: InteractionState,
  id: string,
  source: ActivationSource,
): ActivationResult {
  if (shouldSuppressActivation(state, source)) {
    const next = {
      ...state,
      suppressPointerClick: false,
    };
    return {
      state: {
        ...next,
        phase: isCameraMotionPhase(next.phase)
          ? next.phase
          : restingPhase(next),
      },
      activated: false,
    };
  }

  const next = {
    ...state,
    selectedId: id,
  };
  return {
    state: {
      ...next,
      phase:
        next.pointer || isCameraMotionPhase(next.phase)
          ? next.phase
          : "selected",
    },
    activated: true,
  };
}

export function interactionReducer(
  state: InteractionState,
  event: InteractionEvent,
): InteractionState {
  switch (event.type) {
    case "POINTER_DOWN":
      if (state.pointer) return state;
      return {
        ...state,
        phase: "pointer-down",
        pointer: {
          pointerId: event.pointerId,
          start: { ...event.point },
          current: { ...event.point },
        },
        // A fresh pointer sequence cannot be the click generated by the old one.
        suppressPointerClick: false,
      };

    case "POINTER_MOVE": {
      const pointer = state.pointer;
      if (!pointer || pointer.pointerId !== event.pointerId) return state;

      const nextPointer = {
        ...pointer,
        current: { ...event.point },
      };
      if (
        state.phase !== "dragging" &&
        !hasReachedDragThreshold(pointer.start, event.point)
      ) {
        return { ...state, pointer: nextPointer };
      }

      return {
        ...state,
        phase: "dragging",
        pointer: nextPointer,
        hoveredId: null,
        suppressPointerClick: true,
      };
    }

    case "POINTER_UP": {
      if (!state.pointer || state.pointer.pointerId !== event.pointerId) {
        return state;
      }
      const dragged = state.phase === "dragging";
      const next = {
        ...state,
        pointer: null,
        suppressPointerClick: dragged,
      };
      return {
        ...next,
        phase: restingPhase(next),
      };
    }

    case "POINTER_CANCEL": {
      if (!state.pointer || state.pointer.pointerId !== event.pointerId) {
        return state;
      }
      const next = {
        ...state,
        pointer: null,
        suppressPointerClick: false,
      };
      return {
        ...next,
        phase: restingPhase(next),
      };
    }

    case "HOVER": {
      if (state.phase === "dragging") return state;
      const next = {
        ...state,
        hoveredId: event.id,
      };
      if (state.pointer || isCameraMotionPhase(state.phase)) return next;
      return {
        ...next,
        phase: restingPhase(next),
      };
    }

    case "ACTIVATE":
      return activateInteraction(state, event.id, event.source).state;

    case "DESELECT": {
      const next = {
        ...state,
        selectedId: null,
      };
      if (state.pointer || isCameraMotionPhase(state.phase)) return next;
      return {
        ...next,
        phase: restingPhase(next),
      };
    }

    case "CAMERA_MOTION_START":
      if (state.pointer) return state;
      return {
        ...state,
        phase: event.motion,
      };

    case "CAMERA_MOTION_END":
      if (
        !isCameraMotionPhase(state.phase) ||
        (event.motion && event.motion !== state.phase)
      ) {
        return state;
      }
      return {
        ...state,
        phase: restingPhase(state),
      };

    case "CLEAR_POINTER_CLICK_SUPPRESSION":
      return {
        ...state,
        suppressPointerClick: false,
      };

    case "RESET":
      return createInteractionState();
  }
}
