// ─── Shared Types & Data for Dev Trivia Showdown ─────────────────────────────
// Extracted so both page.tsx (same-device) and OnlineGame.tsx (online) can use them.

export type Category = 'Languages' | 'Frameworks' | 'History' | 'Algorithms' | 'DevOps' | 'Databases' | 'Security' | 'General';
export type Difficulty = 'Easy' | 'Medium' | 'Hard';

export interface TriviaQuestion {
  question: string;
  answers: string[];
  correct: number; // index into answers
  category: Category;
  difficulty: Difficulty;
}

// ─── 200+ Trivia Questions ─────────────────────────────────────

export const QUESTIONS: TriviaQuestion[] = [
  // ── Languages (35) ──
  { question: "Which language was originally called 'Oak'?", answers: ['Java', 'JavaScript', 'C#', 'Kotlin'], correct: 0, category: 'Languages', difficulty: 'Easy' },
  { question: "What does the '++' in C++ represent?", answers: ['Addition operator', 'Increment of C', 'Version 2', 'Double precision'], correct: 1, category: 'Languages', difficulty: 'Easy' },
  { question: "Which language uses 'fn' for function declarations?", answers: ['Go', 'Rust', 'Swift', 'Kotlin'], correct: 1, category: 'Languages', difficulty: 'Medium' },
  { question: "What language is known as the 'jewel' language?", answers: ['Ruby', 'Pearl', 'Crystal', 'Diamond'], correct: 0, category: 'Languages', difficulty: 'Easy' },
  { question: "Which language was created by Guido van Rossum?", answers: ['Perl', 'PHP', 'Python', 'Ruby'], correct: 2, category: 'Languages', difficulty: 'Easy' },
  { question: "What does 'COBOL' stand for?", answers: ['Common Business Oriented Language', 'Computer Binary Object Language', 'Compiled Business Operation Logic', 'Common Byte Oriented Logic'], correct: 0, category: 'Languages', difficulty: 'Medium' },
  { question: "Which language introduced the concept of 'goroutines'?", answers: ['Erlang', 'Go', 'Rust', 'Elixir'], correct: 1, category: 'Languages', difficulty: 'Medium' },
  { question: "What language uses 'let' and 'var' for variable declarations since ES6?", answers: ['TypeScript', 'JavaScript', 'Swift', 'Kotlin'], correct: 1, category: 'Languages', difficulty: 'Easy' },
  { question: "Which language compiles to the Erlang VM (BEAM)?", answers: ['Clojure', 'Elixir', 'Haskell', 'Scala'], correct: 1, category: 'Languages', difficulty: 'Medium' },
  { question: "What language uses indentation instead of braces for blocks?", answers: ['Ruby', 'Lua', 'Python', 'Perl'], correct: 2, category: 'Languages', difficulty: 'Easy' },
  { question: "Which language was developed at Bell Labs in 1972?", answers: ['C', 'Pascal', 'FORTRAN', 'Lisp'], correct: 0, category: 'Languages', difficulty: 'Medium' },
  { question: "What is Kotlin's primary target platform?", answers: ['iOS', 'JVM', 'WebAssembly', '.NET'], correct: 1, category: 'Languages', difficulty: 'Easy' },
  { question: "Which language uses the 'impl' keyword for implementations?", answers: ['Go', 'Rust', 'Swift', 'C++'], correct: 1, category: 'Languages', difficulty: 'Medium' },
  { question: "What language was created by Brendan Eich in 10 days?", answers: ['TypeScript', 'CoffeeScript', 'JavaScript', 'Dart'], correct: 2, category: 'Languages', difficulty: 'Easy' },
  { question: "Which language introduced pattern matching with 'match'?", answers: ['Rust', 'Java', 'C++', 'Go'], correct: 0, category: 'Languages', difficulty: 'Medium' },
  { question: "What is the mascot of the Go programming language?", answers: ['A beaver', 'A gopher', 'A penguin', 'A snake'], correct: 1, category: 'Languages', difficulty: 'Easy' },
  { question: "Which language uses 'defmodule' to define modules?", answers: ['Elixir', 'Erlang', 'Haskell', 'OCaml'], correct: 0, category: 'Languages', difficulty: 'Hard' },
  { question: "What was TypeScript originally codenamed?", answers: ['Strada', 'Dart', 'Flow', 'CoffeeScript'], correct: 0, category: 'Languages', difficulty: 'Hard' },
  { question: "Which language introduced the 'async/await' pattern first?", answers: ['JavaScript', 'C#', 'Python', 'Rust'], correct: 1, category: 'Languages', difficulty: 'Hard' },
  { question: "What does 'PHP' originally stand for?", answers: ['Personal Home Page', 'PHP Hypertext Processor', 'Parsed HTML Protocol', 'Public Hosting Platform'], correct: 0, category: 'Languages', difficulty: 'Medium' },
  { question: "Which language uses 'fun' for function declarations?", answers: ['Kotlin', 'Rust', 'Go', 'Swift'], correct: 0, category: 'Languages', difficulty: 'Medium' },
  { question: "What year was Python first released?", answers: ['1989', '1991', '1995', '2000'], correct: 1, category: 'Languages', difficulty: 'Hard' },
  { question: "Which language has a 'borrow checker'?", answers: ['C++', 'Go', 'Rust', 'Swift'], correct: 2, category: 'Languages', difficulty: 'Medium' },
  { question: "What language was designed for the .NET framework?", answers: ['Java', 'C#', 'F#', 'Visual Basic'], correct: 1, category: 'Languages', difficulty: 'Easy' },
  { question: "Which language uses 'puts' to print output?", answers: ['Python', 'Ruby', 'Go', 'Rust'], correct: 1, category: 'Languages', difficulty: 'Medium' },
  { question: "What language uses ':=' for short variable declaration?", answers: ['Pascal', 'Go', 'Ada', 'Delphi'], correct: 1, category: 'Languages', difficulty: 'Medium' },
  { question: "Which language was created at Sun Microsystems?", answers: ['C#', 'JavaScript', 'Java', 'Ruby'], correct: 2, category: 'Languages', difficulty: 'Easy' },
  { question: "What does 'SQL' stand for?", answers: ['Structured Query Language', 'Simple Query Logic', 'System Query Language', 'Standard Query Library'], correct: 0, category: 'Languages', difficulty: 'Easy' },
  { question: "Which language is named after a type of coffee?", answers: ['Mocha', 'Java', 'Espresso', 'Latte'], correct: 1, category: 'Languages', difficulty: 'Easy' },
  { question: "What language uses 'println!' as a macro for printing?", answers: ['Rust', 'Kotlin', 'Scala', 'Swift'], correct: 0, category: 'Languages', difficulty: 'Medium' },
  { question: "Which language uses 'guard' statements?", answers: ['Kotlin', 'Rust', 'Swift', 'Go'], correct: 2, category: 'Languages', difficulty: 'Medium' },
  { question: "What language introduced 'Option' and 'Result' types?", answers: ['Haskell', 'Rust', 'Scala', 'F#'], correct: 1, category: 'Languages', difficulty: 'Hard' },
  { question: "Which language has 'channels' for concurrency?", answers: ['Go', 'Java', 'Python', 'C++'], correct: 0, category: 'Languages', difficulty: 'Medium' },
  { question: "What does 'LISP' stand for?", answers: ['List Processing', 'Logical Instruction Set Program', 'Linear Interpreted Script Protocol', 'Low-level Interface System Process'], correct: 0, category: 'Languages', difficulty: 'Medium' },
  { question: "Which language is known for its 'zero-cost abstractions'?", answers: ['Go', 'Rust', 'Java', 'Python'], correct: 1, category: 'Languages', difficulty: 'Hard' },

  // ── Frameworks (32) ──
  { question: "Which framework's logo is an atom?", answers: ['Vue', 'Angular', 'React', 'Svelte'], correct: 2, category: 'Frameworks', difficulty: 'Easy' },
  { question: "Which CSS framework is named after a weather phenomenon?", answers: ['Bootstrap', 'Tailwind', 'Bulma', 'Foundation'], correct: 1, category: 'Frameworks', difficulty: 'Easy' },
  { question: "What framework uses a 'Virtual DOM' concept?", answers: ['Angular', 'Svelte', 'React', 'jQuery'], correct: 2, category: 'Frameworks', difficulty: 'Easy' },
  { question: "Which framework was created by Evan You?", answers: ['React', 'Vue', 'Svelte', 'Angular'], correct: 1, category: 'Frameworks', difficulty: 'Medium' },
  { question: "What does 'Next.js' add to React?", answers: ['State management', 'Server-side rendering', 'CSS-in-JS', 'Testing'], correct: 1, category: 'Frameworks', difficulty: 'Easy' },
  { question: "Which framework uses 'directives' like ng-if?", answers: ['React', 'Vue', 'Angular', 'Svelte'], correct: 2, category: 'Frameworks', difficulty: 'Easy' },
  { question: "What Ruby framework follows 'Convention over Configuration'?", answers: ['Sinatra', 'Rails', 'Hanami', 'Roda'], correct: 1, category: 'Frameworks', difficulty: 'Easy' },
  { question: "Which framework compiles away at build time?", answers: ['React', 'Angular', 'Vue', 'Svelte'], correct: 3, category: 'Frameworks', difficulty: 'Medium' },
  { question: "What Python framework is called 'The web framework for perfectionists with deadlines'?", answers: ['Flask', 'Django', 'FastAPI', 'Pyramid'], correct: 1, category: 'Frameworks', difficulty: 'Medium' },
  { question: "Which framework uses 'hooks' like useState and useEffect?", answers: ['Angular', 'Vue 2', 'React', 'Ember'], correct: 2, category: 'Frameworks', difficulty: 'Easy' },
  { question: "What is Express.js built on?", answers: ['Python', 'Node.js', 'Deno', 'Bun'], correct: 1, category: 'Frameworks', difficulty: 'Easy' },
  { question: "Which framework introduced 'Signals' for reactivity?", answers: ['React', 'SolidJS', 'Angular', 'Ember'], correct: 1, category: 'Frameworks', difficulty: 'Hard' },
  { question: "What does 'SPA' stand for in web development?", answers: ['Single Page Application', 'Server Page Architecture', 'Static Page Assembly', 'Simple Programming API'], correct: 0, category: 'Frameworks', difficulty: 'Easy' },
  { question: "Which framework uses .vue single-file components?", answers: ['React', 'Angular', 'Vue', 'Svelte'], correct: 2, category: 'Frameworks', difficulty: 'Easy' },
  { question: "What testing framework uses 'describe' and 'it' blocks?", answers: ['Pytest', 'JUnit', 'Jest', 'PHPUnit'], correct: 2, category: 'Frameworks', difficulty: 'Medium' },
  { question: "Which framework was built by the Laravel creator?", answers: ['Livewire', 'Inertia', 'Both A and B', 'None'], correct: 0, category: 'Frameworks', difficulty: 'Hard' },
  { question: "What is the default bundler for Vite?", answers: ['Webpack', 'Rollup', 'Parcel', 'esbuild'], correct: 3, category: 'Frameworks', difficulty: 'Hard' },
  { question: "Which meta-framework is built for Vue?", answers: ['Next.js', 'Nuxt', 'Remix', 'Gatsby'], correct: 1, category: 'Frameworks', difficulty: 'Medium' },
  { question: "What framework uses the motto 'The Progressive JavaScript Framework'?", answers: ['React', 'Vue', 'Svelte', 'Angular'], correct: 1, category: 'Frameworks', difficulty: 'Medium' },
  { question: "Which CSS framework uses utility-first classes?", answers: ['Bootstrap', 'Tailwind CSS', 'Materialize', 'Bulma'], correct: 1, category: 'Frameworks', difficulty: 'Easy' },
  { question: "What is the primary language for Flutter?", answers: ['Java', 'Kotlin', 'Dart', 'Swift'], correct: 2, category: 'Frameworks', difficulty: 'Medium' },
  { question: "Which framework uses 'getServerSideProps'?", answers: ['Nuxt', 'Next.js', 'Remix', 'Gatsby'], correct: 1, category: 'Frameworks', difficulty: 'Medium' },
  { question: "What framework introduced 'Server Components'?", answers: ['Vue', 'React', 'Svelte', 'Angular'], correct: 1, category: 'Frameworks', difficulty: 'Medium' },
  { question: "Which mobile framework was created by Facebook?", answers: ['Flutter', 'Xamarin', 'React Native', 'Ionic'], correct: 2, category: 'Frameworks', difficulty: 'Easy' },
  { question: "What does 'ORM' stand for?", answers: ['Object Relational Mapping', 'Optimized Runtime Module', 'Object Resource Manager', 'Operational Reference Model'], correct: 0, category: 'Frameworks', difficulty: 'Easy' },
  { question: "Which framework uses 'Blade' templates?", answers: ['Django', 'Rails', 'Laravel', 'Spring'], correct: 2, category: 'Frameworks', difficulty: 'Medium' },
  { question: "What is Astro's key feature?", answers: ['Virtual DOM', 'Islands architecture', 'JIT compilation', 'Hot reloading'], correct: 1, category: 'Frameworks', difficulty: 'Hard' },
  { question: "Which framework uses 'middleware' functions in its request pipeline?", answers: ['Express.js', 'React', 'Vue', 'Svelte'], correct: 0, category: 'Frameworks', difficulty: 'Easy' },
  { question: "What backend framework is built with Rust?", answers: ['Actix', 'Express', 'Django', 'Spring'], correct: 0, category: 'Frameworks', difficulty: 'Hard' },
  { question: "Which framework uses 'zones' for change detection?", answers: ['React', 'Vue', 'Angular', 'Svelte'], correct: 2, category: 'Frameworks', difficulty: 'Hard' },
  { question: "What state management library uses 'reducers'?", answers: ['MobX', 'Zustand', 'Redux', 'Jotai'], correct: 2, category: 'Frameworks', difficulty: 'Medium' },
  { question: "Which framework introduced 'file-based routing'?", answers: ['Next.js', 'Express', 'Django', 'Rails'], correct: 0, category: 'Frameworks', difficulty: 'Medium' },

  // ── History (30) ──
  { question: "What year was the first website published?", answers: ['1989', '1991', '1993', '1995'], correct: 1, category: 'History', difficulty: 'Easy' },
  { question: "Who created Linux?", answers: ['Dennis Ritchie', 'Linus Torvalds', 'Richard Stallman', 'Ken Thompson'], correct: 1, category: 'History', difficulty: 'Easy' },
  { question: "What was the first high-level programming language?", answers: ['COBOL', 'FORTRAN', 'Lisp', 'ALGOL'], correct: 1, category: 'History', difficulty: 'Medium' },
  { question: "Who is considered the father of computer science?", answers: ['John von Neumann', 'Alan Turing', 'Charles Babbage', 'Ada Lovelace'], correct: 1, category: 'History', difficulty: 'Easy' },
  { question: "What year was Git created?", answers: ['2002', '2005', '2008', '2010'], correct: 1, category: 'History', difficulty: 'Medium' },
  { question: "Who created Git?", answers: ['Guido van Rossum', 'Linus Torvalds', 'Ken Thompson', 'Brendan Eich'], correct: 1, category: 'History', difficulty: 'Easy' },
  { question: "What was the first ever computer bug?", answers: ['Memory overflow', 'An actual moth', 'Syntax error', 'Short circuit'], correct: 1, category: 'History', difficulty: 'Medium' },
  { question: "What year was Stack Overflow launched?", answers: ['2006', '2008', '2010', '2012'], correct: 1, category: 'History', difficulty: 'Medium' },
  { question: "Who founded Microsoft?", answers: ['Steve Jobs', 'Bill Gates & Paul Allen', 'Larry Page', 'Mark Zuckerberg'], correct: 1, category: 'History', difficulty: 'Easy' },
  { question: "What was Amazon's original product?", answers: ['Electronics', 'Books', 'Cloud computing', 'Groceries'], correct: 1, category: 'History', difficulty: 'Easy' },
  { question: "What year was the iPhone introduced?", answers: ['2005', '2006', '2007', '2008'], correct: 2, category: 'History', difficulty: 'Easy' },
  { question: "Who invented the World Wide Web?", answers: ['Vint Cerf', 'Tim Berners-Lee', 'Marc Andreessen', 'Robert Kahn'], correct: 1, category: 'History', difficulty: 'Easy' },
  { question: "What was the first graphical web browser?", answers: ['Netscape', 'Mosaic', 'Internet Explorer', 'Opera'], correct: 1, category: 'History', difficulty: 'Medium' },
  { question: "What company created the first hard drive?", answers: ['Intel', 'IBM', 'HP', 'Texas Instruments'], correct: 1, category: 'History', difficulty: 'Medium' },
  { question: "What year did GitHub launch?", answers: ['2006', '2008', '2010', '2012'], correct: 1, category: 'History', difficulty: 'Medium' },
  { question: "What does 'HTTP' stand for?", answers: ['HyperText Transfer Protocol', 'High Tech Transfer Process', 'Hyper Transfer Text Protocol', 'HyperText Transmission Protocol'], correct: 0, category: 'History', difficulty: 'Easy' },
  { question: "Who created the first compiler?", answers: ['Ada Lovelace', 'Grace Hopper', 'Alan Turing', 'John McCarthy'], correct: 1, category: 'History', difficulty: 'Hard' },
  { question: "What year was Node.js released?", answers: ['2007', '2009', '2011', '2013'], correct: 1, category: 'History', difficulty: 'Medium' },
  { question: "Which company developed the UNIX operating system?", answers: ['IBM', 'Microsoft', 'Bell Labs', 'Xerox'], correct: 2, category: 'History', difficulty: 'Medium' },
  { question: "What was Google's original name?", answers: ['BackRub', 'PageRank', 'SearchBot', 'WebCrawl'], correct: 0, category: 'History', difficulty: 'Hard' },
  { question: "What year was Docker released?", answers: ['2011', '2013', '2015', '2017'], correct: 1, category: 'History', difficulty: 'Hard' },
  { question: "Who co-founded Apple with Steve Jobs?", answers: ['Bill Gates', 'Steve Wozniak', 'Tim Cook', 'John Sculley'], correct: 1, category: 'History', difficulty: 'Easy' },
  { question: "What does 'ASCII' stand for?", answers: ['American Standard Code for Information Interchange', 'Automated System Code for Internet Integration', 'American System for Computer Information Interchange', 'Advanced Standard Code for Information Integration'], correct: 0, category: 'History', difficulty: 'Medium' },
  { question: "What was the first programming language used in space?", answers: ['FORTRAN', 'Assembly', 'HAL/S', 'Ada'], correct: 2, category: 'History', difficulty: 'Hard' },
  { question: "When was the first email sent?", answers: ['1965', '1971', '1975', '1981'], correct: 1, category: 'History', difficulty: 'Hard' },
  { question: "What company developed Java?", answers: ['Microsoft', 'Sun Microsystems', 'IBM', 'Oracle'], correct: 1, category: 'History', difficulty: 'Easy' },
  { question: "What year was Kubernetes first released?", answers: ['2012', '2014', '2016', '2018'], correct: 1, category: 'History', difficulty: 'Hard' },
  { question: "Who is credited as the first computer programmer?", answers: ['Grace Hopper', 'Ada Lovelace', 'Alan Turing', 'Charles Babbage'], correct: 1, category: 'History', difficulty: 'Medium' },
  { question: "What year was TypeScript released?", answers: ['2010', '2012', '2014', '2016'], correct: 1, category: 'History', difficulty: 'Medium' },
  { question: "What company bought GitHub in 2018?", answers: ['Google', 'Amazon', 'Microsoft', 'Facebook'], correct: 2, category: 'History', difficulty: 'Easy' },

  // ── Algorithms (30) ──
  { question: "What's the time complexity of binary search?", answers: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'], correct: 1, category: 'Algorithms', difficulty: 'Easy' },
  { question: "Which sorting algorithm is also called 'sinking sort'?", answers: ['Selection sort', 'Bubble sort', 'Insertion sort', 'Merge sort'], correct: 1, category: 'Algorithms', difficulty: 'Easy' },
  { question: "What data structure uses FIFO?", answers: ['Stack', 'Queue', 'Tree', 'Graph'], correct: 1, category: 'Algorithms', difficulty: 'Easy' },
  { question: "What data structure uses LIFO?", answers: ['Queue', 'Stack', 'Heap', 'Array'], correct: 1, category: 'Algorithms', difficulty: 'Easy' },
  { question: "What's the worst-case time complexity of quicksort?", answers: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'], correct: 2, category: 'Algorithms', difficulty: 'Medium' },
  { question: "What algorithm finds the shortest path in a weighted graph?", answers: ['BFS', 'DFS', "Dijkstra's", 'Binary search'], correct: 2, category: 'Algorithms', difficulty: 'Medium' },
  { question: "What is the time complexity of accessing an element in a hash table?", answers: ['O(n)', 'O(log n)', 'O(1) average', 'O(n log n)'], correct: 2, category: 'Algorithms', difficulty: 'Easy' },
  { question: "Which sort is stable and has O(n log n) guaranteed?", answers: ['Quicksort', 'Merge sort', 'Heap sort', 'Radix sort'], correct: 1, category: 'Algorithms', difficulty: 'Medium' },
  { question: "What technique solves problems by breaking them into overlapping subproblems?", answers: ['Divide and conquer', 'Dynamic programming', 'Greedy', 'Backtracking'], correct: 1, category: 'Algorithms', difficulty: 'Medium' },
  { question: "What is a 'balanced' binary search tree?", answers: ['All leaves at same level', 'Height difference <= 1', 'Equal left and right nodes', 'No duplicate values'], correct: 1, category: 'Algorithms', difficulty: 'Medium' },
  { question: "What does BFS stand for?", answers: ['Binary File Search', 'Breadth-First Search', 'Best-First Sort', 'Batch File System'], correct: 1, category: 'Algorithms', difficulty: 'Easy' },
  { question: "What is the space complexity of merge sort?", answers: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'], correct: 2, category: 'Algorithms', difficulty: 'Medium' },
  { question: "Which data structure is used in BFS?", answers: ['Stack', 'Queue', 'Heap', 'Tree'], correct: 1, category: 'Algorithms', difficulty: 'Easy' },
  { question: "What is a 'trie' used for?", answers: ['Sorting numbers', 'String/prefix searching', 'Graph traversal', 'Memory management'], correct: 1, category: 'Algorithms', difficulty: 'Medium' },
  { question: "What's the best-case time complexity of bubble sort?", answers: ['O(1)', 'O(n)', 'O(n log n)', 'O(n^2)'], correct: 1, category: 'Algorithms', difficulty: 'Medium' },
  { question: "What is Big O notation used for?", answers: ['Memory allocation', 'Describing algorithm efficiency', 'Error handling', 'Code formatting'], correct: 1, category: 'Algorithms', difficulty: 'Easy' },
  { question: "What problem does the 'Traveling Salesman' address?", answers: ['Graph coloring', 'Shortest route visiting all nodes', 'Network flow', 'String matching'], correct: 1, category: 'Algorithms', difficulty: 'Medium' },
  { question: "What is the time complexity of inserting at the beginning of a linked list?", answers: ['O(n)', 'O(log n)', 'O(1)', 'O(n^2)'], correct: 2, category: 'Algorithms', difficulty: 'Easy' },
  { question: "Which algorithm is used for finding minimum spanning trees?", answers: ["Dijkstra's", "Kruskal's", 'Floyd-Warshall', 'Bellman-Ford'], correct: 1, category: 'Algorithms', difficulty: 'Hard' },
  { question: "What is 'memoization'?", answers: ['Saving memory', 'Caching function results', 'Writing documentation', 'Garbage collection'], correct: 1, category: 'Algorithms', difficulty: 'Medium' },
  { question: "What is the maximum number of children in a binary tree node?", answers: ['1', '2', '3', 'Unlimited'], correct: 1, category: 'Algorithms', difficulty: 'Easy' },
  { question: "What type of tree is used in most database indexes?", answers: ['Binary tree', 'Red-black tree', 'B-tree', 'AVL tree'], correct: 2, category: 'Algorithms', difficulty: 'Hard' },
  { question: "What is the time complexity of finding an element in a sorted array?", answers: ['O(n)', 'O(log n)', 'O(1)', 'O(n^2)'], correct: 1, category: 'Algorithms', difficulty: 'Easy' },
  { question: "What algorithm does Git use for diffing?", answers: ['KMP', 'Myers diff', 'Rabin-Karp', 'Levenshtein'], correct: 1, category: 'Algorithms', difficulty: 'Hard' },
  { question: "What is a 'heap' data structure primarily used for?", answers: ['Sorting strings', 'Priority queue', 'Stack operations', 'Linked list traversal'], correct: 1, category: 'Algorithms', difficulty: 'Medium' },
  { question: "What is the time complexity of heap sort?", answers: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'], correct: 1, category: 'Algorithms', difficulty: 'Medium' },
  { question: "What does 'NP-hard' mean?", answers: ['Not Possible to solve', 'At least as hard as NP-complete', 'Needs Parallelism', 'Non-Polynomial time only'], correct: 1, category: 'Algorithms', difficulty: 'Hard' },
  { question: "What is a 'collision' in hashing?", answers: ['Two keys mapping to same index', 'Hash table overflow', 'Memory leak', 'Stack overflow'], correct: 0, category: 'Algorithms', difficulty: 'Easy' },
  { question: "Which traversal visits root, then left, then right?", answers: ['Inorder', 'Preorder', 'Postorder', 'Level order'], correct: 1, category: 'Algorithms', difficulty: 'Medium' },
  { question: "What is amortized O(1) mean?", answers: ['Always O(1)', 'O(1) on average over many operations', 'O(1) in best case', 'O(1) with caching'], correct: 1, category: 'Algorithms', difficulty: 'Hard' },

  // ── DevOps (26) ──
  { question: "What does 'CI/CD' stand for?", answers: ['Code Integration / Code Delivery', 'Continuous Integration / Continuous Delivery', 'Computer Interface / Computer Deployment', 'Centralized Integration / Centralized Deployment'], correct: 1, category: 'DevOps', difficulty: 'Easy' },
  { question: "What is Docker used for?", answers: ['Version control', 'Containerization', 'Testing', 'Monitoring'], correct: 1, category: 'DevOps', difficulty: 'Easy' },
  { question: "What does 'K8s' stand for?", answers: ['Kafka', 'Kubernetes', 'Kibana', 'Knative'], correct: 1, category: 'DevOps', difficulty: 'Easy' },
  { question: "What is Terraform used for?", answers: ['Container orchestration', 'Infrastructure as Code', 'Monitoring', 'Log management'], correct: 1, category: 'DevOps', difficulty: 'Medium' },
  { question: "What is the default port for HTTPS?", answers: ['80', '443', '8080', '3000'], correct: 1, category: 'DevOps', difficulty: 'Easy' },
  { question: "What does 'DNS' stand for?", answers: ['Digital Network System', 'Domain Name System', 'Data Network Service', 'Distributed Node Server'], correct: 1, category: 'DevOps', difficulty: 'Easy' },
  { question: "What is a 'reverse proxy'?", answers: ['A proxy that blocks traffic', 'A server that forwards requests to backend servers', 'A VPN', 'A firewall'], correct: 1, category: 'DevOps', difficulty: 'Medium' },
  { question: "Which tool is known for 'Infrastructure as Code' with YAML?", answers: ['Terraform', 'Ansible', 'Docker', 'Git'], correct: 1, category: 'DevOps', difficulty: 'Medium' },
  { question: "What is the purpose of a load balancer?", answers: ['Encrypt traffic', 'Distribute traffic across servers', 'Cache data', 'Compress files'], correct: 1, category: 'DevOps', difficulty: 'Easy' },
  { question: "What does 'SSH' stand for?", answers: ['Secure Shell', 'Safe Server Hosting', 'System Shell Handler', 'Secure System Hub'], correct: 0, category: 'DevOps', difficulty: 'Easy' },
  { question: "What is Prometheus used for?", answers: ['Container orchestration', 'Monitoring and alerting', 'CI/CD pipelines', 'Secret management'], correct: 1, category: 'DevOps', difficulty: 'Medium' },
  { question: "What Kubernetes resource defines a desired pod state?", answers: ['Service', 'Deployment', 'ConfigMap', 'Ingress'], correct: 1, category: 'DevOps', difficulty: 'Medium' },
  { question: "What is a 'microservice'?", answers: ['A small server', 'An independently deployable service', 'A JavaScript library', 'A testing framework'], correct: 1, category: 'DevOps', difficulty: 'Easy' },
  { question: "What is 'blue-green deployment'?", answers: ['Running two identical production environments', 'A testing strategy', 'A monitoring tool', 'A Docker feature'], correct: 0, category: 'DevOps', difficulty: 'Medium' },
  { question: "What tool did GitHub Actions replace for many users?", answers: ['Jenkins', 'Travis CI', 'CircleCI', 'All of the above'], correct: 3, category: 'DevOps', difficulty: 'Medium' },
  { question: "What is a 'canary deployment'?", answers: ['Deploying to a subset of users first', 'Deploying to all users at once', 'Rolling back a deployment', 'A testing strategy'], correct: 0, category: 'DevOps', difficulty: 'Hard' },
  { question: "What does 'YAML' stand for?", answers: ['Yet Another Markup Language', "YAML Ain't Markup Language", 'Your Application Markup Language', 'Yielded Automated Markup Logic'], correct: 1, category: 'DevOps', difficulty: 'Medium' },
  { question: "What is the default port for HTTP?", answers: ['443', '8080', '80', '3000'], correct: 2, category: 'DevOps', difficulty: 'Easy' },
  { question: "What is Grafana used for?", answers: ['Container runtime', 'Visualization and dashboards', 'Version control', 'Package management'], correct: 1, category: 'DevOps', difficulty: 'Medium' },
  { question: "What does 'CDN' stand for?", answers: ['Content Distribution Network', 'Content Delivery Network', 'Centralized Data Node', 'Cloud Deployment Network'], correct: 1, category: 'DevOps', difficulty: 'Easy' },
  { question: "What is Vault by HashiCorp used for?", answers: ['Container orchestration', 'Secret management', 'Log aggregation', 'CI/CD'], correct: 1, category: 'DevOps', difficulty: 'Hard' },
  { question: "What is the '12-factor app' methodology about?", answers: ['12 programming languages', 'Best practices for SaaS apps', '12 testing strategies', '12 deployment stages'], correct: 1, category: 'DevOps', difficulty: 'Hard' },
  { question: "What protocol does Docker use to build images?", answers: ['HTTP', 'BuildKit', 'gRPC', 'REST'], correct: 1, category: 'DevOps', difficulty: 'Hard' },
  { question: "What is 'horizontal scaling'?", answers: ['Adding more RAM', 'Adding more servers', 'Adding more CPUs', 'Adding more storage'], correct: 1, category: 'DevOps', difficulty: 'Easy' },
  { question: "What is an 'ingress' in Kubernetes?", answers: ['A pod type', 'An API for managing external access', 'A storage volume', 'A namespace'], correct: 1, category: 'DevOps', difficulty: 'Medium' },
  { question: "What is 'GitOps'?", answers: ['A Git GUI', 'Using Git as single source of truth for infrastructure', 'A CI/CD tool', 'A code review practice'], correct: 1, category: 'DevOps', difficulty: 'Medium' },

  // ── Databases (26) ──
  { question: "What type of database is MongoDB?", answers: ['Relational', 'Document/NoSQL', 'Graph', 'Time series'], correct: 1, category: 'Databases', difficulty: 'Easy' },
  { question: "What does 'ACID' stand for in databases?", answers: ['Atomicity, Consistency, Isolation, Durability', 'Automated, Centralized, Integrated, Distributed', 'Asynchronous, Cached, Indexed, Distributed', 'Atomicity, Cached, Isolated, Duplicated'], correct: 0, category: 'Databases', difficulty: 'Medium' },
  { question: "What SQL command retrieves data?", answers: ['GET', 'FETCH', 'SELECT', 'RETRIEVE'], correct: 2, category: 'Databases', difficulty: 'Easy' },
  { question: "What is Redis primarily used for?", answers: ['File storage', 'In-memory caching', 'Graph queries', 'Full-text search'], correct: 1, category: 'Databases', difficulty: 'Easy' },
  { question: "What does 'ORM' do?", answers: ['Optimizes queries', 'Maps objects to database tables', 'Manages connections', 'Encrypts data'], correct: 1, category: 'Databases', difficulty: 'Easy' },
  { question: "What is a 'primary key'?", answers: ['The first column', 'A unique identifier for each row', 'The most important data', 'An encrypted field'], correct: 1, category: 'Databases', difficulty: 'Easy' },
  { question: "What database type uses nodes and edges?", answers: ['Relational', 'Document', 'Graph', 'Key-value'], correct: 2, category: 'Databases', difficulty: 'Medium' },
  { question: "What is 'sharding' in databases?", answers: ['Deleting old data', 'Splitting data across multiple servers', 'Encrypting data', 'Compressing tables'], correct: 1, category: 'Databases', difficulty: 'Medium' },
  { question: "What does 'JOIN' do in SQL?", answers: ['Merges databases', 'Combines rows from two or more tables', 'Creates a new table', 'Deletes duplicate rows'], correct: 1, category: 'Databases', difficulty: 'Easy' },
  { question: "What is PostgreSQL known as?", answers: ['The Oracle killer', 'The most advanced open source database', 'MySQL Pro', 'SQLite Plus'], correct: 1, category: 'Databases', difficulty: 'Medium' },
  { question: "What is a 'foreign key'?", answers: ['A key from another country', 'A reference to a primary key in another table', 'An encrypted key', 'A deprecated key'], correct: 1, category: 'Databases', difficulty: 'Easy' },
  { question: "What is 'normalization' in databases?", answers: ['Making data normal', 'Organizing data to reduce redundancy', 'Resetting the database', 'Converting to uppercase'], correct: 1, category: 'Databases', difficulty: 'Medium' },
  { question: "What is a 'deadlock'?", answers: ['A locked database', 'Two transactions waiting for each other forever', 'A crashed server', 'A corrupted table'], correct: 1, category: 'Databases', difficulty: 'Medium' },
  { question: "What does 'CAP theorem' state?", answers: ['Consistency, Availability, Partition tolerance - pick 2', 'Cache, API, Performance must balance', 'Create, Alter, Purge are fundamental', 'Compute, Access, Process must optimize'], correct: 0, category: 'Databases', difficulty: 'Hard' },
  { question: "What is SQLite?", answers: ['A cloud database', 'An embedded file-based database', 'A NoSQL database', 'A distributed database'], correct: 1, category: 'Databases', difficulty: 'Easy' },
  { question: "What is an 'index' in a database?", answers: ['The first row', 'A data structure improving query speed', 'A table of contents', 'A backup system'], correct: 1, category: 'Databases', difficulty: 'Easy' },
  { question: "What is 'eventual consistency'?", answers: ['Data is always consistent', 'Data will become consistent over time', 'Data is never consistent', 'Consistency is optional'], correct: 1, category: 'Databases', difficulty: 'Hard' },
  { question: "What type of database is Neo4j?", answers: ['Relational', 'Document', 'Graph', 'Columnar'], correct: 2, category: 'Databases', difficulty: 'Medium' },
  { question: "What is a 'transaction' in databases?", answers: ['A payment', 'A unit of work that is atomic', 'A query log', 'A data transfer'], correct: 1, category: 'Databases', difficulty: 'Easy' },
  { question: "What does 'CRUD' stand for?", answers: ['Create, Read, Update, Delete', 'Cache, Route, Upload, Download', 'Connect, Retrieve, Update, Disconnect', 'Compile, Run, Upload, Deploy'], correct: 0, category: 'Databases', difficulty: 'Easy' },
  { question: "What is Cassandra designed for?", answers: ['Small datasets', 'High availability distributed data', 'Graph queries', 'In-memory caching'], correct: 1, category: 'Databases', difficulty: 'Medium' },
  { question: "What SQL clause filters grouped results?", answers: ['WHERE', 'HAVING', 'FILTER', 'GROUP BY'], correct: 1, category: 'Databases', difficulty: 'Medium' },
  { question: "What is a 'view' in SQL?", answers: ['A database diagram', 'A virtual table based on a query', 'A type of index', 'A user interface'], correct: 1, category: 'Databases', difficulty: 'Medium' },
  { question: "What is 'write-ahead logging' (WAL)?", answers: ['Writing logs before commits for crash recovery', 'A logging framework', 'Writing ahead of schedule', 'A backup strategy'], correct: 0, category: 'Databases', difficulty: 'Hard' },
  { question: "What is a 'materialized view'?", answers: ['A view with CSS', 'A precomputed query result stored on disk', 'A graphical view', 'A temporary table'], correct: 1, category: 'Databases', difficulty: 'Hard' },
  { question: "What is connection pooling?", answers: ['Swimming database', 'Reusing database connections', 'Merging databases', 'Load balancing queries'], correct: 1, category: 'Databases', difficulty: 'Medium' },

  // ── Security (26) ──
  { question: "What does 'XSS' stand for?", answers: ['Cross-Site Scripting', 'Extra Secure System', 'XML Security Standard', 'Cross-Server Sync'], correct: 0, category: 'Security', difficulty: 'Easy' },
  { question: "What is 'SQL injection'?", answers: ['Adding SQL to a database', 'Inserting malicious SQL through user input', 'A type of database', 'SQL performance tuning'], correct: 1, category: 'Security', difficulty: 'Easy' },
  { question: "What does 'HTTPS' add to HTTP?", answers: ['Speed', 'Encryption via TLS/SSL', 'Compression', 'Caching'], correct: 1, category: 'Security', difficulty: 'Easy' },
  { question: "What is a 'JWT'?", answers: ['Java Web Token', 'JSON Web Token', 'JavaScript Web Tool', 'Joint Work Ticket'], correct: 1, category: 'Security', difficulty: 'Easy' },
  { question: "What does 'CORS' stand for?", answers: ['Cross-Origin Resource Sharing', 'Centralized Origin Request System', 'Common Origin Resource Security', 'Cross-Object Reference Standard'], correct: 0, category: 'Security', difficulty: 'Medium' },
  { question: "What is 'CSRF'?", answers: ['Cross-Site Request Forgery', 'Centralized Server Request Format', 'Common Security Review Framework', 'Cross-System Resource Filter'], correct: 0, category: 'Security', difficulty: 'Medium' },
  { question: "What is 'OAuth' used for?", answers: ['Database access', 'Authorization delegation', 'Encryption', 'File transfer'], correct: 1, category: 'Security', difficulty: 'Medium' },
  { question: "What is a 'man-in-the-middle' attack?", answers: ['An insider threat', 'Intercepting communication between two parties', 'A brute force attack', 'A phishing scam'], correct: 1, category: 'Security', difficulty: 'Medium' },
  { question: "What does 'OWASP' stand for?", answers: ['Open Web Application Security Project', 'Online Web API Security Protocol', 'Open Wireless Application Standard Process', 'Official Web Application Security Platform'], correct: 0, category: 'Security', difficulty: 'Medium' },
  { question: "What is 'hashing' used for in security?", answers: ['Encrypting files', 'One-way transformation of data', 'Compressing data', 'Sorting data'], correct: 1, category: 'Security', difficulty: 'Easy' },
  { question: "What is 'two-factor authentication'?", answers: ['Two passwords', 'Two different verification methods', 'Two user accounts', 'Two security questions'], correct: 1, category: 'Security', difficulty: 'Easy' },
  { question: "What is a 'DDoS' attack?", answers: ['Data theft', 'Overwhelming a server with traffic', 'SQL injection', 'Phishing'], correct: 1, category: 'Security', difficulty: 'Easy' },
  { question: "What hashing algorithm is NOT recommended for passwords?", answers: ['bcrypt', 'Argon2', 'MD5', 'scrypt'], correct: 2, category: 'Security', difficulty: 'Medium' },
  { question: "What is 'rate limiting'?", answers: ['Slowing network speed', 'Restricting the number of requests', 'Charging per API call', 'Limiting database rows'], correct: 1, category: 'Security', difficulty: 'Easy' },
  { question: "What is the purpose of a 'salt' in password hashing?", answers: ['Flavor', 'Adding random data to prevent rainbow table attacks', 'Encrypting the hash', 'Compressing the password'], correct: 1, category: 'Security', difficulty: 'Medium' },
  { question: "What is 'phishing'?", answers: ['Catching fish online', 'Tricking users into revealing sensitive info', 'A type of malware', 'Network scanning'], correct: 1, category: 'Security', difficulty: 'Easy' },
  { question: "What does 'TLS' stand for?", answers: ['Transport Layer Security', 'Total Layer System', 'Transfer Link Security', 'Trusted Login Service'], correct: 0, category: 'Security', difficulty: 'Medium' },
  { question: "What is a 'zero-day vulnerability'?", answers: ['A vulnerability found on day zero of release', 'An unknown exploit with no available fix', 'A vulnerability that takes zero days to fix', 'A harmless vulnerability'], correct: 1, category: 'Security', difficulty: 'Hard' },
  { question: "What is 'Content Security Policy' (CSP)?", answers: ['A privacy policy', 'HTTP header to prevent XSS and injection', 'A database policy', 'A cloud security tool'], correct: 1, category: 'Security', difficulty: 'Hard' },
  { question: "What is 'RBAC'?", answers: ['Remote Backup and Control', 'Role-Based Access Control', 'Real-time Breach Alert Center', 'Rapid Backup and Cache'], correct: 1, category: 'Security', difficulty: 'Medium' },
  { question: "What is 'encryption at rest'?", answers: ['Encrypting data during transfer', 'Encrypting stored data', 'Encrypting while sleeping', 'Encrypting backups only'], correct: 1, category: 'Security', difficulty: 'Medium' },
  { question: "What is a 'honeypot' in security?", answers: ['A trap system to detect attackers', 'A password manager', 'An encryption method', 'A firewall type'], correct: 0, category: 'Security', difficulty: 'Hard' },
  { question: "What protocol replaced SSL?", answers: ['HTTPS', 'TLS', 'SSH', 'IPSec'], correct: 1, category: 'Security', difficulty: 'Medium' },
  { question: "What is 'least privilege principle'?", answers: ['Minimum server resources', 'Giving minimum necessary access rights', 'Lowest priority processes', 'Least expensive security solution'], correct: 1, category: 'Security', difficulty: 'Medium' },
  { question: "What is 'penetration testing'?", answers: ['Stress testing servers', 'Authorized simulated attacks to find vulnerabilities', 'Testing database performance', 'Testing API endpoints'], correct: 1, category: 'Security', difficulty: 'Medium' },
  { question: "What is a 'keylogger'?", answers: ['A key management tool', 'Software that records keystrokes', 'A debugging tool', 'An authentication system'], correct: 1, category: 'Security', difficulty: 'Easy' },

  // ── General (25) ──
  { question: "What does 'API' stand for?", answers: ['Application Programming Interface', 'Automated Program Integration', 'Application Process Identifier', 'Advanced Programming Instruction'], correct: 0, category: 'General', difficulty: 'Easy' },
  { question: "What does 'IDE' stand for?", answers: ['Internet Development Environment', 'Integrated Development Environment', 'Intelligent Design Editor', 'Internal Debug Engine'], correct: 1, category: 'General', difficulty: 'Easy' },
  { question: "What is 'localhost'?", answers: ['A web hosting service', 'Your own computer (127.0.0.1)', 'A cloud server', 'A local network'], correct: 1, category: 'General', difficulty: 'Easy' },
  { question: "What is a '404' error?", answers: ['Server error', 'Not found', 'Unauthorized', 'Bad request'], correct: 1, category: 'General', difficulty: 'Easy' },
  { question: "What does 'JSON' stand for?", answers: ['JavaScript Object Notation', 'Java Standard Object Network', 'JavaScript Online Network', 'JSON Server Object Name'], correct: 0, category: 'General', difficulty: 'Easy' },
  { question: "What is 'pair programming'?", answers: ['Two computers connected', 'Two developers working together on one task', 'Programming in pairs of functions', 'A code review process'], correct: 1, category: 'General', difficulty: 'Easy' },
  { question: "What does 'DRY' stand for in programming?", answers: ['Debug, Refactor, Yield', 'Do Repeat Yourself', "Don't Repeat Yourself", 'Data Representation Yield'], correct: 2, category: 'General', difficulty: 'Easy' },
  { question: "What is 'technical debt'?", answers: ['Money owed for software', 'Shortcuts that create future maintenance work', 'Cost of cloud hosting', 'Software licensing fees'], correct: 1, category: 'General', difficulty: 'Easy' },
  { question: "What is a '500' error?", answers: ['Not found', 'Unauthorized', 'Internal server error', 'Bad gateway'], correct: 2, category: 'General', difficulty: 'Easy' },
  { question: "What does 'MVP' mean in product development?", answers: ['Most Valuable Programmer', 'Minimum Viable Product', 'Maximum Viable Performance', 'Managed Version Platform'], correct: 1, category: 'General', difficulty: 'Easy' },
  { question: "What is 'agile' methodology?", answers: ['Moving fast', 'Iterative and incremental development', 'A programming language', 'A testing framework'], correct: 1, category: 'General', difficulty: 'Easy' },
  { question: "What is a 'code smell'?", answers: ['Bad variable names', 'Signs of potential design problems', 'A syntax error', 'A runtime exception'], correct: 1, category: 'General', difficulty: 'Medium' },
  { question: "What does 'SOLID' represent?", answers: ['5 principles of OOP design', 'A programming language', 'A database technique', 'A testing methodology'], correct: 0, category: 'General', difficulty: 'Medium' },
  { question: "What is 'refactoring'?", answers: ['Rewriting from scratch', 'Improving code structure without changing behavior', 'Adding new features', 'Fixing bugs'], correct: 1, category: 'General', difficulty: 'Easy' },
  { question: "What is a 'race condition'?", answers: ['A performance test', 'Behavior depending on timing of events', 'A type of deadlock', 'A network issue'], correct: 1, category: 'General', difficulty: 'Medium' },
  { question: "What does 'SaaS' stand for?", answers: ['Software as a Service', 'System as a Solution', 'Server and Application Service', 'Secure Application as Software'], correct: 0, category: 'General', difficulty: 'Easy' },
  { question: "What is 'rubber duck debugging'?", answers: ['Using a rubber duck for stress relief', 'Explaining code to an inanimate object to find bugs', 'A testing tool', 'A code review process'], correct: 1, category: 'General', difficulty: 'Medium' },
  { question: "What is 'semantic versioning'?", answers: ['Naming versions with words', 'MAJOR.MINOR.PATCH numbering', 'Date-based versioning', 'Random version numbers'], correct: 1, category: 'General', difficulty: 'Medium' },
  { question: "What does 'KISS' stand for?", answers: ['Keep It Simple, Stupid', 'Keep It Secure and Safe', 'Knowledge In Software Systems', 'Key Integration System Standard'], correct: 0, category: 'General', difficulty: 'Easy' },
  { question: "What is a 'monorepo'?", answers: ['A single repository for one project', 'A repository containing multiple projects', 'A private repository', 'A read-only repository'], correct: 1, category: 'General', difficulty: 'Medium' },
  { question: "What is 'DevOps'?", answers: ['A programming language', 'Culture of collaboration between dev and ops', 'A deployment tool', 'A testing methodology'], correct: 1, category: 'General', difficulty: 'Easy' },
  { question: "What is 'linting'?", answers: ['Removing lint from code', 'Static analysis to find potential errors', 'Compiling code', 'Formatting output'], correct: 1, category: 'General', difficulty: 'Easy' },
  { question: "What does 'YAGNI' stand for?", answers: ["You Aren't Gonna Need It", 'Your Application Generates New Issues', 'Yet Another General Network Interface', 'Your API Gets No Input'], correct: 0, category: 'General', difficulty: 'Medium' },
  { question: "What is 'scope creep'?", answers: ['A variable scope bug', 'Uncontrolled expansion of project requirements', 'A security vulnerability', 'A memory leak'], correct: 1, category: 'General', difficulty: 'Medium' },
  { question: "What is a 'pull request'?", answers: ['Downloading code', 'Proposing changes for review before merging', 'Requesting access', 'Pulling data from an API'], correct: 1, category: 'General', difficulty: 'Easy' },
];

// ─── Category Metadata ──────────────────────────────────────────
export const CATEGORY_META: Record<Category, { icon: string; color: string }> = {
  Languages: { icon: '{ }', color: 'var(--color-accent)' },
  Frameworks: { icon: '< >', color: 'var(--color-blue)' },
  History: { icon: '...', color: 'var(--color-orange)' },
  Algorithms: { icon: 'O()', color: 'var(--color-purple)' },
  DevOps: { icon: '>>>', color: 'var(--color-cyan)' },
  Databases: { icon: '[=]', color: 'var(--color-pink)' },
  Security: { icon: '***', color: 'var(--color-red)' },
  General: { icon: '?!?', color: 'var(--color-orange)' },
};

export const ALL_CATEGORIES: Category[] = ['Languages', 'Frameworks', 'History', 'Algorithms', 'DevOps', 'Databases', 'Security', 'General'];
export const TEAM_NAMES = ['ALPHA', 'BETA'] as const;
export const TEAM_COLORS = ['var(--color-accent)', 'var(--color-blue)'] as const;
